// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1rTr3wFGxMbeJUBDm22kKqy7BRylyayQ',
    appId: '1:1048303927122:web:b1dcc59806e040f8cf448b',
    messagingSenderId: '1048303927122',
    projectId: 'heydoc-2f2ba',
    authDomain: 'heydoc-2f2ba.firebaseapp.com',
    storageBucket: 'heydoc-2f2ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfaDqgCx7lFdspq7ZxkB7caoHVhfFyMwg',
    appId: '1:1048303927122:android:2b9b4b9dbf2a3a03cf448b',
    messagingSenderId: '1048303927122',
    projectId: 'heydoc-2f2ba',
    storageBucket: 'heydoc-2f2ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFQDLYDMGBrLtrzSAkMiIIhHQzNi65Bgo',
    appId: '1:1048303927122:ios:4732628ab3e5c546cf448b',
    messagingSenderId: '1048303927122',
    projectId: 'heydoc-2f2ba',
    storageBucket: 'heydoc-2f2ba.appspot.com',
    iosClientId: '1048303927122-ci2tmdeq96c9e0kk2jvqbtp1m4k9f2en.apps.googleusercontent.com',
    iosBundleId: 'com.example.heydocapp',
  );
}
