// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6vJ6v6NfUZ5JjDbxCWhT-qzXsJJpZciA',
    appId: '1:1026544214579:web:82942c7511ea1a93f6b946',
    messagingSenderId: '1026544214579',
    projectId: 'hey-doc-new',
    authDomain: 'hey-doc-new.firebaseapp.com',
    storageBucket: 'hey-doc-new.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKwUdF7fRBpNLuOhhYCKw9i6GtdfclUPA',
    appId: '1:1026544214579:android:a680f0765daa3434f6b946',
    messagingSenderId: '1026544214579',
    projectId: 'hey-doc-new',
    storageBucket: 'hey-doc-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiOQMJYjp-OB1oxgkHtb9kc0x722Kv3Rk',
    appId: '1:1026544214579:ios:fadd606c73fefd52f6b946',
    messagingSenderId: '1026544214579',
    projectId: 'hey-doc-new',
    storageBucket: 'hey-doc-new.appspot.com',
    iosBundleId: 'com.example.heydocapp',
  );

}